spring:
    application:
        name: trainer-workload-service
    data:
        mongodb:
            uri: mongodb://localhost:27017/trainer-workload-db  # URL de conexión a MongoDB
            database: trainer-workload-db  # Nombre de la base de datos
    activemq:
        broker-url: tcp://localhost:61616
        user: admin
        password: admin

server:
    port: 0

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
        preferIpAddress: true

jwt:
    secret: signatureSecret183827374628384628274628364627836482738
